name: "Hola Mundo"
description: "Greet someone"
inputs:
  comando:
    description: "lo que sea"
    required: true
runs:
  using: “composite”
  
  steps:
    - uses: actions/checkout@v3
      
    - run: echo ${{ inputs.comando }}
      shell: bash
        
