name: "Hola Mundo"
description: "Greet someone"
inputs:
  who-to-greet:  # id of input
    description: "Who to greet"
    required: false
    default: "World"
    
  another-input:
    description: "lo que sea"
    required: true
outputs:
  output-variable:
    description: "wahteva"
    value: ${{ steps.prueba.outputs.output-variable }}
runs:
  using: “composite”
  
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}
      shell: bash
      
    - id: prueba
      run: |
        echo "::set-output name=output-variable::"
        echo ${{ inputs.another-input }}
      shell: bash
