name: ‘Hola Mundo’
description: ‘Greet someone’
inputs:
  who-to-greet:  # id of input
    description: ‘Who to greet’
    required: true
    default: ‘World’
outputs:
  random-number:
    description: “Random number”
    value: ${{ steps.prueba.outputs.output-variable }}
  output-variable:
    description: "wahteva"
    value: ${{ steps.prueba.outputs.output-variable }}
runs:
  using: “composite”
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}
      shell: bash
    - id: random-number-generator
      run: echo “::set-output name=random-number::$(echo $RANDOM)”
      shell: bash
    - run: echo “${{ github.action_path }}” >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
      
    - id: prueba
      run: echo "::set-output name=output-variable::"
      shell: bash
      
    - run: mvn test
      shell: bash
