name: "Hola Mundo"
description: "Greet someone"
inputs:
  who-to-greet:  # id of input
    description: "Who to greet"
    required: false
    default: "World"
    
  comando:
    description: "lo que sea"
    required: true
runs:
  using: “composite”
  
  steps:
    - uses: actions/checkout@v3
    
    - run: echo Hello ${{ inputs.who-to-greet }}
      shell: bash
      
    - run: echo ${{ inputs.comando }}
      shell: bash
        
