name: 'Hola Mundo'
description: 'Greet someone'
inputs:
  entrada1:
    description: 'lo que sea'
    required: true

outputs:
  hovno:
    description: 'whatever'
    value: ${{ steps.salidita.outputs.hovno }}

runs:
  using: 'composite'
  
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.entrada1 }}
        
    - id: salidita
      run: |
        echo "::set-output name=hovno::"
        echo ${{ inputs.comando }}
      shell: bash
        
