name: 'Hola Mundo'
description: 'Greet someone'
inputs:
  comando:
    description: 'lo que sea'
    required: true

outputs:
  salida:
    description: 'whatever'
    value: ${{ steps.salidita.outputs.hovno }}

runs:
  using: 'composite'
  
  steps:
    - uses: actions/checkout@v3
    
    - id: salidita
      run: |
        echo "::set-output name=hovno::"
        ${{ inputs.comando }}
      shell: bash
        
