name: 'Hola Mundo'
description: 'Greet someone'
inputs:
  entrada1:
    description: 'lo que sea'
    required: true
    
  entrada2:
    description: 'hola'
    required: true

runs:
  using: 'composite'
  
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.entrada1 }}
        ref: ${{ inputs.entrada2 }}
        
    - run: mvn test
        
